title: Yonggyun (YG) Kim
# logo: /assets/img/logo.png
description: YG's webpage
# show_downloads: false
# google_analytics:
theme: jekyll-theme-minimal

 git config --global user.email "yonggyun.yg.kim@gmail.com"
